services:
  readme.file-vault.mongo:
    image: mongo:4.4
    restart: always
    container_name: readme.file-vault.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - ${MONGO_PORT}:27018

    volumes:
      - readme.mongo.file-vault:/data/db

  readme.file-vault.mongo.ui:
    image: mongo-express:1.0-20
    restart: always
    container_name: readme.file-vault.mongo.ui
    ports:
      - 8083:8083
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@readme.file-vault.mongo:${MONGO_PORT}/

volumes:
  readme.mongo.file-vault:
